export function EditorTimeline(acordesSincronizados, zoomLevel, duration) {
    const width = duration * zoomLevel;

    return `
        <div id="timeline-area" class="h-72 bg-gray-800 border-t border-gray-700 flex flex-col relative select-none">
            
            <!-- Timeline Header (Ruler) -->
            <div class="h-6 bg-gray-900 border-b border-gray-700 relative overflow-hidden" id="timeline-ruler">
                <!-- Time markers generated by JS (omitted for brevity in HTML string, usually dynamic) -->
            </div>

            <!-- Tracks Container -->
            <div class="flex-1 relative overflow-hidden overflow-x-auto" id="timeline-tracks">
                
                <!-- Playhead -->
                <div id="playhead" class="absolute top-0 bottom-0 w-0.5 bg-blue-500 z-30 pointer-events-none" style="left: 0px;">
                    <div class="w-3 h-3 bg-blue-500 rounded-full -ml-1.5 -mt-1.5"></div>
                </div>

                <!-- Track: Chords -->
                <div class="h-12 border-b border-gray-700 relative bg-gray-800/50" id="track-chords" style="width: ${width}px;">
                    ${renderTimelineChords(acordesSincronizados, zoomLevel)}
                </div>

                <!-- Track: Waveform -->
                <div class="h-24 relative bg-gray-900/50" id="track-waveform" style="width: ${width}px;">
                    <canvas id="waveform-canvas" class="w-full h-full opacity-60"></canvas>
                </div>

            </div>
        </div>
    `;
}

function renderTimelineChords(acordesSincronizados, zoomLevel) {
    return acordesSincronizados.map(acorde => {
        const left = acorde.tiempo_inicio * zoomLevel;
        const width = (acorde.tiempo_fin - acorde.tiempo_inicio) * zoomLevel;

        return `
            <div class="chord-block absolute top-1 h-10 rounded shadow-sm border border-white/20 flex items-center justify-center text-xs font-bold text-white cursor-pointer select-none overflow-hidden group"
                 style="left: ${left}px; width: ${Math.max(width, 20)}px; background-color: ${acorde.color_hex || '#34d399'};"
                 data-id="${acorde.id_sincronia_acorde}">
                ${acorde.nombre_acorde}
                
                <!-- Resize Handles -->
                <div class="absolute left-0 top-0 bottom-0 w-2 cursor-w-resize bg-black/20 hover:bg-white/50 opacity-0 group-hover:opacity-100 transition-opacity handle-l"></div>
                <div class="absolute right-0 top-0 bottom-0 w-2 cursor-e-resize bg-black/20 hover:bg-white/50 opacity-0 group-hover:opacity-100 transition-opacity handle-r"></div>
            </div>
        `;
    }).join('');
}
