CREATE TABLE IF NOT EXISTS ESTROFA (
    id_estrofa INT AUTO_INCREMENT PRIMARY KEY,
    id_cancion INT(10) UNSIGNED NOT NULL,
    contenido TEXT NOT NULL,
    orden INT DEFAULT 0,
    tiempo_inicio DECIMAL(10,3) DEFAULT 0,
    tiempo_fin DECIMAL(10,3) DEFAULT 0,
    FOREIGN KEY (id_cancion) REFERENCES CANCION(id_cancion) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
